[build.environment]
  NODE_VERSION = "20.19.5"
  NPM_VERSION = "10.8.2"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_SKIP_LIGHTNINGCSS = "true"

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
